development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:84d2638644ea10a558714035c1e341ce@pike.redistogo.com:10840/
  channel_prefix: Fidget_production
